name: Deploy Server
on:
  push:
    branches:
      - main
    paths:
      - 'apps/server/**'
jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with: 
          version: '0.1.135'
      - name: Deploy
        working-directory: apps/server
        run: ./deploy.sh
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
